# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
permalink: /:title
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll
title: Korean CR Project
tagline: "by B.F.M."

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Korean CR Project

description: Korean CR Project Homepage by B.F.M.
author:
  name: B.F.M.
#  email: bfm@example.com
  github: youbeebee
#  twitter: asd123
#  pinterest: asd123
#  linkedin: asd123
  bio: 'B.F.M. <br>DCI 공인 MTG Lv.1 Judge'
#  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
